// Generated by https://quicktype.io
import { Area } from './area';

export interface CompetitionsData {
    count:        number;
    filters:      CompetitionFilters;
    competitions: Competition[];
}

export interface Competition {
    id:                       number;
    area:                     Area;
    name:                     string;
    code:                     string;
    plan:                     Plan;
    currentSeason:            CurrentSeason;
    numberOfAvailableSeasons: number;
    lastUpdated:              string;
}

export interface CurrentSeason {
    id:              number;
    startDate:       string;
    endDate:         string;
    currentMatchday: number;
}

export enum Plan {
    TierFour = "TIER_FOUR",
    TierOne = "TIER_ONE",
    TierThree = "TIER_THREE",
    TierTwo = "TIER_TWO",
}

export interface CompetitionFilters {
    areas: string;
    plan: string;
}
